# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.2
        DEFAULT_BUMP: patch

    outputs:
        new_version: ${{ steps.tab_bump.outputs.new_tag }}

  build-and-deploy-service:

    runs-on: ubuntu-latest
    needs: generate-version

    env:
      APP_NAME: iga1playeconomy
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
    
      with:
        # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT=${{secrets.GH_PAT}}"
        # List of tags
        tags: ${{env.APP_NAME}}.azurecr.io/play.trading:${{ needs.generate-version.outputs.new_version }}
